from pathlib import Path
import re
p=Path('/home/ubuntu/kentankclient/src/App.tsx')
s=p.read_text()
s=s.replace("const [bannerBusy, setBannerBusy] = useState(false); const [bannerMessage, setBannerMessage] = useState('');", "const [bannerBusy, setBannerBusy] = useState(false); const [bannerMessage, setBannerMessage] = useState(''); const [editingBanner, setEditingBanner] = useState<number | null>(null);")
pattern=r"  const saveBanner = async \(event: FormEvent\) => \{.*?\n  const changeBanner = async"
replacement="""  const saveBanner = async (event: FormEvent) => { event.preventDefault(); setBannerBusy(true); setBannerMessage(''); try { const isEditing = editingBanner !== null; const response = await fetch(`${API}/api/admin/banners${isEditing ? `/${editingBanner}` : ''}`, { method: isEditing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...banner, sort_order: Number(banner.sort_order) }) }); if (!response.ok) throw new Error('Could not save banner'); const saved = await response.json(); setAdminBanners(isEditing ? adminBanners.map(item => item.id === editingBanner ? saved : item) : [...adminBanners, saved]); setBanner({ eyebrow: 'Kentank', title: '', body: '', image_url: '', cta_label: 'Explore the collection', cta_url: '/catalogue', placement: 'home_hero', active: true, sort_order: adminBanners.length + 1 }); setEditingBanner(null); setBannerMessage(isEditing ? 'Banner updated successfully.' : 'Banner saved successfully.'); } catch (error) { setBannerMessage(error instanceof Error ? error.message : 'Could not save banner.'); } finally { setBannerBusy(false) } };
  const editBanner = (item: Banner) => { setEditingBanner(item.id); setBanner({ eyebrow: item.eyebrow, title: item.title, body: item.body, image_url: item.image_url || '', cta_label: item.cta_label, cta_url: item.cta_url, placement: item.placement || 'home_hero', active: item.active, sort_order: item.sort_order }); setBannerMessage('Editing this banner.'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const cancelBannerEdit = () => { setEditingBanner(null); setBanner({ eyebrow: 'Kentank', title: '', body: '', image_url: '', cta_label: 'Explore the collection', cta_url: '/catalogue', placement: 'home_hero', active: true, sort_order: adminBanners.length + 1 }); setBannerMessage(''); };
  const changeBanner = async"""
s,n=re.subn(pattern,replacement,s,flags=re.S)
if n!=1: raise SystemExit(f'saveBanner block replacements: {n}')
s=s.replace('<h2>Homepage banners</h2></div></div><form className="product-editor" onSubmit={saveBanner}>', '<h2>{editingBanner ? \'Edit homepage banner\' : \'Homepage banners\'}</h2></div></div><form className="product-editor" onSubmit={saveBanner}>')
s=s.replace("<div className=\"editor-actions full-field\"><button className=\"primary-button\" disabled={bannerBusy}>{bannerBusy ? <Spinner label=\"Saving…\" /> : <>Save banner <span>↗</span></>}</button></div>", "<div className=\"editor-actions full-field\"><button className=\"primary-button\" disabled={bannerBusy}>{bannerBusy ? <Spinner label=\"Saving…\" /> : <>{editingBanner ? 'Update banner' : 'Save banner'} <span>↗</span></>}</button>{editingBanner && <button type=\"button\" className=\"text-link\" onClick={cancelBannerEdit}>Cancel edit</button>}</div>")
s=s.replace('<button onClick={() => changeBanner(item, { sort_order: Math.max(0, item.sort_order - 1) })}>Move up</button>', '<button onClick={() => editBanner(item)}>Edit</button><button onClick={() => changeBanner(item, { sort_order: Math.max(0, item.sort_order - 1) })}>Move up</button>')
p.write_text(s)

css=Path('/home/ubuntu/kentankclient/src/App.css')
css.write_text(css.read_text()+"\n.product-thumb{width:100%;height:210px;border-radius:18px;overflow:hidden;background:#edf4f1;display:block}.product-thumb img{width:100%;height:100%;object-fit:cover;display:block}.product-row .product-index{position:absolute;top:16px;left:18px;z-index:1}.product-row{position:relative}.product-row .product-name{padding-top:2px}.admin-row-image{width:54px;height:54px;object-fit:cover;border-radius:12px}.banner-admin-card{min-height:170px}.banner-admin-card>img{height:150px}\n")
